import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";

// Hard fallbacks so the app never boots with undefined backend env vars.
// (These are publishable values and already present in the project environment.)
const FALLBACK_PROJECT_ID = "znisxrjrqyziddmnirmz";
const FALLBACK_URL = `https://${FALLBACK_PROJECT_ID}.supabase.co`;
const FALLBACK_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuaXN4cmpycXl6aWRkbW5pcm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5ODQ0MDIsImV4cCI6MjA4MDU2MDQwMn0.hk-si3vtceQY4WtCX2nvznUqGAUcwDdX-RZOIhS5K1g";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  // Ensure the autogenerated backend client never sees undefined env vars.
  define: {
    "import.meta.env.VITE_SUPABASE_PROJECT_ID": JSON.stringify(
      process.env.VITE_SUPABASE_PROJECT_ID ?? FALLBACK_PROJECT_ID
    ),
    "import.meta.env.VITE_SUPABASE_URL": JSON.stringify(
      process.env.VITE_SUPABASE_URL ?? FALLBACK_URL
    ),
    "import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY": JSON.stringify(
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? FALLBACK_PUBLISHABLE_KEY
    ),
    "import.meta.env.VITE_SUPABASE_ANON_KEY": JSON.stringify(
      process.env.VITE_SUPABASE_ANON_KEY ??
        process.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
        FALLBACK_PUBLISHABLE_KEY
    ),
  },
  server: {
    host: "::",
    port: 8080,
  },
  plugins: [react(), mode === "development" && componentTagger()].filter(Boolean),
  resolve: {
    alias: [
      {
        find: /^@\/integrations\/supabase\/client(\.ts)?$/,
        replacement: path.resolve(__dirname, "./src/integrations/supabase/client-runtime.ts"),
      },
      {
        find: "@",
        replacement: path.resolve(__dirname, "./src"),
      },
    ],
  },
}));
