// Runtime-safe Supabase client wrapper.
// We keep the autogenerated client.ts untouched and route imports here via Vite alias.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Prefer environment variables, but provide robust fallbacks for builds where Vite env injection fails.
const FALLBACK_PROJECT_ID = "znisxrjrqyziddmnirmz";
const FALLBACK_URL = `https://${FALLBACK_PROJECT_ID}.supabase.co`;
const FALLBACK_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuaXN4cmpycXl6aWRkbW5pcm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5ODQ0MDIsImV4cCI6MjA4MDU2MDQwMn0.hk-si3vtceQY4WtCX2nvznUqGAUcwDdX-RZOIhS5K1g";

const projectId = (import.meta as any).env?.VITE_SUPABASE_PROJECT_ID as string | undefined;
const envUrl = (import.meta as any).env?.VITE_SUPABASE_URL as string | undefined;

// Some Lovable Cloud projects expose the publishable key as VITE_SUPABASE_PUBLISHABLE_KEY.
const envKey =
  ((import.meta as any).env?.VITE_SUPABASE_ANON_KEY as string | undefined) ||
  ((import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined);

export const BACKEND_URL = envUrl || (projectId ? `https://${projectId}.supabase.co` : undefined) || FALLBACK_URL;
export const BACKEND_PUBLISHABLE_KEY = envKey || FALLBACK_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(BACKEND_URL, BACKEND_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
